RD-24 Working with repositories
aurity/react-style-guidelines pull request #2
Opened 2017-04-05 14:30 UTC by phuzarski

2 cases to consider:
- Creating the new branch and push it to GitHub
- Push code to existing repository

Feel free to comment.

2017-04-05 14:36 UTC, PeterKow requested changes
can you add info how good PR looks like:

Clean, small pieces of code
eslint + tests before final commit
check your PR and compare with ticket requirements before releasing to others
add link to jira ticket in PR notes
take a print screen or use Licecap or Gayzao to record a screen

2017-04-05 14:36 UTC, PeterKow commented on README.md
> +## Working with repositories
can we move this to different file => `docs/gitflow` so this readme it;s not too long

2017-04-05 14:40 UTC, PeterKow commented
can you also add info about a review process:
-> create PR 
-> check your PR
-> share on slack and put into "review" column in Jira
->  PR should be reviewed by at lease two people and  👍 x2  when all comments are solved
-> after review ticket can be QA (move in Jira)

-> PR should be created again base branch `develop`

2017-04-05 16:53 UTC, phuzarski commented
The changes:

[main README](https://i.gyazo.com/188bffbb9b8222aec74eb41fcd44edf6.png)

[docs/gitflow/README](https://i.gyazo.com/6723199e5b79627eb4e8b9a29d30a8b1.png)

2017-04-06 11:02 UTC, 8Pablo commented
Nice one Patryk.

2017-04-06 15:07 UTC, Bran1304 commented
Looking good

2017-04-06 22:13 UTC, PeterKow requested changes
Last changes and ready to go

2017-04-06 22:13 UTC, PeterKow commented on docs/gitflow/README.md
> +### `git checkout -b <name_of_your_new_branch>`
` branch name should be `feature/name_<jira-ticket>`

2017-04-06 22:13 UTC, PeterKow commented on docs/gitflow/README.md
> +If you've copied a project repository, cloned it down to your local system, and added a Git remote to your clone that point to the original repository on GitHub, now you're ready to make some changes
we can mention that SourceTree is a good tool to manage your repos

2017-04-06 22:13 UTC, PeterKow commented on docs/gitflow/README.md
> +4. In description adding a link to Jira ticket.
In description adding a link to Jira ticket and notes if any + screenshot (I think I've sent you also tools for making gifs)

2017-04-07 06:57 UTC, thepatrykk commented
![SourceTree, Gyazo](https://i.gyazo.com/4ff4b03e47e9d6a95ea5b69db812b223.png)

2017-04-07 08:32 UTC, PeterKow approved these changes

2017-04-07 08:32 UTC, merged